version: "2"
linters:
  default: all
  disable:
    - cyclop # We don't focus on arbitrary complexity metrics here.
    - contextcheck # Too many false positives (e.g., during graceful shutdowns).
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert # When you know, you know ;)
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gocognit # We don't focus on arbitrary complexity metrics here.
    - gocyclo # We don't focus on arbitrary complexity metrics here.
    - godot
    - godox
    - gosmopolitan
    - ireturn
    - lll # golines already handle that job.
    - makezero
    - mnd
    - nlreturn
    - noinlineerr
    - nonamedreturns
    - paralleltest # https://groups.google.com/g/golang-dev/c/RAKiqi44GEU/m/WkD64zvPR_0J
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl # Too strict and opinionated. Doesn't necessarily improve code readability.
    - wsl_v5

  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: math/rand$
              desc: Please use math/rand/v2
            - pkg: github.com/pkg/errors
              desc: Please use stdlib instead

    gocritic:
      disabled-checks:
        - singleCaseSwitch
        - appendAssign
      settings:
        ifElseChain:
          minThreshold: 3

    gosec:
      excludes:
        # False positive when using math/rand/v2.
        # https://github.com/securego/gosec/issues/1241
        - G404

    funcorder:
      # We just want logical ordering.
      struct-method: false

    revive:
      rules:
        # We don't focus on arbitrary complexity metrics here.
        - name: cognitive-complexity
          disabled: true
        - name: cyclomatic
          disabled: true
        # Sometimes you don't mandatorily want comments(e.g. implementing an interface)
        - name: package-comments
          disabled: true

    sloglint:
      # Less error-prone(report false-positive when arguments on multi-lines)
      # kv-only: true
      # Use dependency injection instead.
      no-global: "all"
      # https://go.dev/wiki/CodeReviewComments#error-strings
      msg-style: capitalized
      key-naming-case: camel

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          # Don't mandatorily need context in tests
          - noctx

formatters:
  enable:
    - gofumpt
    - goimports
    - golines

  settings:
    gofumpt:
      module-path: github.com/matthieugusmini/take-home
      extra-rules: true

    goimports:
      local-prefixes:
        - github.com/matthieugusmini/take-home

  exclusions:
    generated: lax
