//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
)

// AnyObject Any JSON object
type AnyObject map[string]interface{}

// EncryptResponse Object with same keys as input, all depth-1 values encoded as base64 strings
type EncryptResponse map[string]string

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// SignResponse defines model for SignResponse.
type SignResponse struct {
	// Signature HMAC-SHA256 signature encoded as lowercase hex
	Signature string `json:"signature"`
}

// VerifyRequest defines model for VerifyRequest.
type VerifyRequest struct {
	// Data Any JSON object
	Data AnyObject `json:"data"`

	// Signature HMAC-SHA256 signature (lowercase hex)
	Signature string `json:"signature"`
}

// PostDecryptJSONRequestBody defines body for PostDecrypt for application/json ContentType.
type PostDecryptJSONRequestBody = AnyObject

// PostEncryptJSONRequestBody defines body for PostEncrypt for application/json ContentType.
type PostEncryptJSONRequestBody = AnyObject

// PostSignJSONRequestBody defines body for PostSign for application/json ContentType.
type PostSignJSONRequestBody = AnyObject

// PostVerifyJSONRequestBody defines body for PostVerify for application/json ContentType.
type PostVerifyJSONRequestBody = VerifyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Base64-decode depth-1 string values (if decodable) back to their original JSON values
	// (POST /decrypt)
	PostDecrypt(w http.ResponseWriter, r *http.Request)
	// Base64-encode all depth-1 values of the JSON object
	// (POST /encrypt)
	PostEncrypt(w http.ResponseWriter, r *http.Request)
	// Create an HMAC signature for the JSON object (order-independent)
	// (POST /sign)
	PostSign(w http.ResponseWriter, r *http.Request)
	// Verify an HMAC signature against the provided JSON object
	// (POST /verify)
	PostVerify(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDecrypt operation middleware
func (siw *ServerInterfaceWrapper) PostDecrypt(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDecrypt(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEncrypt operation middleware
func (siw *ServerInterfaceWrapper) PostEncrypt(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEncrypt(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostSign operation middleware
func (siw *ServerInterfaceWrapper) PostSign(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostSign(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostVerify operation middleware
func (siw *ServerInterfaceWrapper) PostVerify(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostVerify(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/decrypt", wrapper.PostDecrypt)
	m.HandleFunc("POST "+options.BaseURL+"/encrypt", wrapper.PostEncrypt)
	m.HandleFunc("POST "+options.BaseURL+"/sign", wrapper.PostSign)
	m.HandleFunc("POST "+options.BaseURL+"/verify", wrapper.PostVerify)

	return m
}
